spring.application.name=smartmeal

# ==========================================
# CONFIGURAÇÃO DE CONEXÃO - POSTGRESQL (SUPABASE)
# ==========================================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# HIBERNATE / JPA
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# MONGODB (NoSQL)
# ==========================================
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=smartmeal_nosql

# ==========================================
# GOOGLE GEMINI API
# ==========================================
gemini.api.key=${GOOGLE_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent